### ISSUE TITLE
React App: Module not found: Can't resolve '@newrelic/browser-agent/loaders/browser-agent'

### ISSUE THREAD

**Issue by vinaykumar515** [newrelic/newrelic-browser-agent#1079] opened 2024-06-20 18:01 UTC
Node: v18.20.3
Npm: 10.7.0
Yarn:1.22.22
Browser: Chrome
OS: Windows
@newrelic/browser-agent": "^1.260.1",

I have taken this resource as reference and implemented same as mentioned, I have installed node module using yarn add command, I can see the node module under node_modules and the same has been added to package.json but still I am seeing the below error.

Error:
./src/App.js
Module not found: Can't resolve '@newrelic/browser-agent/loaders/browser-agent' in 'D:\dev\projects\pas-express-ui\src'

I have this code in App.js

import { BrowserAgent }  from '@newrelic/browser-agent/loaders/browser-agent';  --> Causing the error

if (process.env.REACT_APP_NR_DT_ENABLED === 'true') {
          const nrConfiguration = {
            init: JSON.parse(process.env.REACT_APP_NR_DT_INIT),
            info: JSON.parse(process.env.REACT_APP_NR_DT_INFO),
            loader_config: JSON.parse(process.env.REACT_APP_NR_DT_LOADER_CONFIG),
          }
          new BrowserAgent(nrConfiguration);
  }

**I tried moving the code to index.js, index.html, and also tried loading the script from external js file but still the issue not resolved.**

I even tried upgrading node to v20  and latest version

Any help is appreciated, thank you

**Comment by patrickhousley** [comment] 2024-06-25 13:46
Hi @vinaykumar515 . I am taking a look at this issue today. Can you provide a small reproduction project for this issue? We have [test cases](https://github.com/newrelic/newrelic-browser-agent/blob/main/tools/test-builds/browser-agent-wrapper/src/browser-agent.js) in the project to verify the import statements and those tests are still passing. Unfortunately the node/js ecosystem is a mess of tools and configurations and we may simply be missing something that is unique to your project.

**Comment by vinaykumar515** [comment] 2024-06-25 15:35
Here is my package.json
{
  "name": "dash",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@eisgroup/builder": "1.8.11",
    "@eisgroup/builder-components": "21.8.0",
    "@eisgroup/form": "21.8.0",
    "@eisgroup/form-core": "21.8.0",
    "@eisgroup/ui-desktop": "1.8.11",
    "@emotion/react": "11.10.4",
    "@emotion/styled": "11.10.4",
    "@fontsource/cabin": "^4.5.6",
    "@fortawesome/fontawesome-svg-core": "1.2.36",
    "@fortawesome/free-solid-svg-icons": "5.15.4",
    "@fortawesome/react-fontawesome": "0.1.15",
    "@mui/icons-material": "5.10.6",
    "@mui/material": "5.10.8",
    "@mui/x-data-grid": "5.17.5",
    "@reach/dialog": "0.16.0",
    "axios": "0.21.3",
    "custom-event-polyfill": "1.0.7",
    "date-input-polyfill": "2.14.0",
    "fast-json-patch": "3.1.1",
    "font-awesome": "4.7.0",
    "history": "5.0.1",
    "jest-date-mock": "^1.0.10",
    "json-logic-js": "^2.0.1",
    "latest": "0.2.0",
    "lodash.clonedeep": "4.5.0",
    "lodash.get": "4.4.2",
    "lodash.merge": "4.6.2",
    "lodash.set": "4.3.2",
    "moment": "2.29.4",
    "object-hash": "2.2.0",
    "query-string": "7.0.1",
    "raleway-webfont-alt-w": "^1.0.0",
    "react": "17.0.2",
    "react-app-polyfill": "2.0.0",
    "react-device-detect": "1.17.0",
    "react-dom": "17.0.2",
    "react-idle-timer": "4.6.4",
    "react-iframe": "1.8.0",
    "react-number-format": "4.7.3",
    "react-promise-tracker": "2.1.0",
    "react-router": "5.2.0",
    "react-router-dom": "5.2.0",
    "react-scripts": "4.0.3"
  },
  "devDependencies": {
    "@types/react-router-dom": "5.1.8",
    "prettier": "2.3.2",
    "typescript": "4.3.5"
  },
  "scripts": {
    "start": "react-scripts --openssl-legacy-provider start",
    "build": "react-scripts --openssl-legacy-provider --max_old_space_size=4096 build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "build:oc": "env-cmd -f .env.oc npm run build"
  },
  "eslintConfig": {
    "extends": "react-app",
    "rules": {
      "react-hooks/exhaustive-deps": "off"
    }
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}


Install the @newrelic/browser-agent@1.260.1 using the yarn add command - yarn add @newrelic/browser-agent@1.260.1
keep the import statement in src/index.js file (or) src/App.js file
import { BrowserAgent } from '@newrelic/browser-agent/loaders/browser-agent'
compile and run project using yarn start
you will see the below error
Module not found: Can't resolve '@newrelic/browser-agent/loaders/browser-agent' 

Note: If I create a brand new create-react-app project it is working fine
suspecting something an issue with my existing project

**Comment by patrickhousley** [comment] 2024-06-25 15:42
It looks like your are using a types package, are you using typescript for your JS project? What is your tsconfig?

**Comment by vinaykumar515** [comment] 2024-06-25 15:44
This is my tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "noImplicitAny": false,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "downlevelIteration": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": [
    "src"
  ]
}

**Comment by patrickhousley** [comment] 2024-06-25 15:50
OK so most likely it is one or a combination of options in your tsconfig that is causing issues. Or maybe an outdated version of typescript. We use [conditional exports](https://nodejs.org/docs/latest-v20.x/api/packages.html#conditional-exports) in our package.json.

**Comment by vinaykumar515** [comment] 2024-06-25 15:56
ok, thank you. What could be the fix in my case?
If I upgrade typescript to a latest version - will it work?

**Comment by patrickhousley** [comment] 2024-06-25 15:58
I cannot say exactly what would fix your project. Every project is unique and the node/js tooling ecosystem is diverse. I would suggest reading through the typescript docs, node docs, and trying different settings. If you need further help, I really will need an exact replication project to poke at. For now, I am going to close this issue since it's a project specific configuration.

**Closed by patrickhousley** 2024-06-25 15:58 UTC
Labels: bug

**Comment by vinaykumar515** [comment] 2024-06-25 22:24
Will it be possible to connect with me for few mins on zoom? need your help to triage the issue.

**Comment by patrickhousley** [comment] 2024-06-26 00:17
@vinaykumar515 Unfortunately, if you need that level of support, the best thing to do would be to reach out to the New Relic Support team. https://support.newrelic.com/s/

**Comment by vinaykumar515** [comment] 2024-06-26 22:36
Hello @patrickhousley 
Can you confirm this please
Does @newrelic/browser-agent node module supports react-scripts:4.0.3 version? I am seeing the issue with version 4.0.3 not seen in 5.0.1. If it supports version 4.0.3, I will look more into version conflicts and other potential causes around react-scripts.
As I can use only version 4.0.3 in my project, do you suggest any fixes to make this work in version 4.0.3.

**Comment by patrickhousley** [comment] 2024-06-27 18:54
We do not provide a statement of support for any third party libraries per se. Instead, our top design goal is to be as agnostic to the customer's code/site as possible and just work. However, we have noted some incompatibilities with some third party libraries in our [docs](https://docs.newrelic.com/docs/browser/single-page-app-monitoring/troubleshooting/nextjs-app-router-links-broken/).
