### ISSUE TITLE
UI freezes on iOS/MacOS Safari when using Browser agent

### ISSUE THREAD

**Issue by SultanAitakyn** [newrelic/newrelic-browser-agent#960] opened 2024-04-09 16:50 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## When trying to navigate and change the route, the web app freezes due to using the Browser agent.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )
I wanted to connect New Relic to my React application. I instantiated the agent using your example. Everything works correctly on the desktop Chrome browser, but not in IOS Safari/Chrome and some cases MacOS Safari.

## Steps to Reproduce
1. React app with Browser agent. Add any element that changes the route when clicked
2. Open IOS Safari/Chrome -> Run and open application -> click on element -> UI Freezes.
3. Open MacOS Safari -> Run and open application -> click on element -> refresh the page -> click on element -> UI Freezes., 

## Expected Behavior
UI does not freeze when navigating inside the app on IOS Safari/Chrome, Mac OS Safari. 

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. Include as many of the following as possible:)
No logs in dev tools, the UI just freezes. 

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
Mac OS Safari 16.3
IOS Safari latest

**Comment by patrickhousley** [comment] 2024-05-06 15:10
Hi @SultanAitakyn and thanks for reporting this issue. We have not heard of anyone else having this issue so it may be something specific with your project setup. Would it be possible for you to provide a small replication of the issue that we can use to test? Thanks in advance!

**Comment by patrickhousley** [comment] 2024-05-13 19:40
Closing issue due to a lack of information. There are no other reports of safari issues indicating the issue is specific to the OP project.

**Closed by patrickhousley** 2024-05-13 19:40 UTC
Labels: bug, customer Input

**Comment by jefvlamings** [comment] 2024-07-08 08:51
I'd like to reopen this issue. We're experiencing the same issues and believe this is due to a JS bug causing an infinite loop. 
iOS safari doesn't seem to handle it well which might be the reason why it fails there and not in other browsers.

We use the newrelic_rpm gem (version 9.9)

The browser agent version seems to be `1.261.2`

Screenshot of console:
<img width="1461" alt="Screenshot 2024-07-08 at 10 43 30" src="https://github.com/newrelic/newrelic-browser-agent/assets/1597286/59ff53f7-4d03-48db-91fe-43cd8f98093a">

Code under line 22440 looks like this:

```js
                                t.on("propagate", (function(e, r, n) {
                                    this.getCtx && !r || (this.getCtx = function() {
                                        if (e instanceof Promise)
                                            var r = t.context(e);
                                        return r && r.getCtx ? r.getCtx() : this
                                    }
                                    )
                                }
```

**Comment by patrickhousley** [comment] 2024-07-08 17:33
Hi @jefvlamings I would recommend reaching out to your New Relic support POC to get further support for this issue. That way, we can get a lot more info on your account and issue to troubleshoot. They will be able to open a ticket for us.
