### ISSUE TITLE
Typescript Newrelic Browser agent don't have noticeError method

### ISSUE THREAD

**Issue by master96** [newrelic/newrelic-browser-agent#895] opened 2024-02-15 17:45 UTC
[NOTE]: # ( ^^ Wrong types for Browser Agent ^^ )

## Description

[NOTE]: # ( When BrowserAgent is initialized it exposes noticeError method but when object is logged there is no such method available. It's actually inside api key of browser agent )

NoticeError function is missing from BrowserAgent it's available inside api key but not typed.

## Steps to Reproduce

I have following code 

```javascript
import { BrowserAgent } from '@newrelic/browser-agent/loaders/browser-agent';

export let newrelicWebClient: BrowserAgent;
  const options = {
    init: {
      distributed_tracing: { enabled: true },
      privacy: { cookies_enabled: true },
      ajax: { deny_list: ['*****'] },
    }, // NREUM.init
    info: {
      beacon: '*****',
      errorBeacon: '*****',
      licenseKey: '*****',
      applicationID: '*****',
      sa: 1,
    }, // NREUM.info
    loader_config: {
      accountID: '*****',
      trustKey: '*****',
      agentID: '*****',
      licenseKey: '*****',
      applicationID: '*****',
    }, // NREUM.loader_config
  };

  // The agent loader code executes immediately on instantiation.
  newrelicWebClient = new BrowserAgent(options);
  newrelicWebClient?.setApplicationVersion('*****' || null);


and i am calling it like

console.log(newrelicWebClient);
 newrelicWebClient?.noticeError(e,{some_key:'value'})
 
```
in console log i get 

![image](https://github.com/newrelic/newrelic-browser-agent/assets/12187986/817e254d-59ae-4a60-a8e9-6e597e8833eb)

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version - Chrome
* ex: Operating System and version - Mac
* Browser agent version involved (e.g., v1.229.0) - "@newrelic/browser-agent": "1.251.0",
* APM language and version, if applicable (e.g., Dotnet 10.2.0), and auto|manual

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by patrickhousley** [comment] 2024-02-16 15:44
Hi @master96 and thanks for reaching out. Are you getting a specific error? The method is there, you just have to drill down the inheritance chain.

<img width="908" alt="image" src="https://github.com/newrelic/newrelic-browser-agent/assets/3984979/55299063-8293-418e-9d27-ef8291d1d6c1">

**Comment by master96** [comment] 2024-02-16 18:39
Hello Patrick,

Thanks for getting back to me.

I solved the problem but had to go through script route as my new relic
config needs to be fetched first and then initialized. My code is in react
so what happens is by the time my config is returned via API, DOM is
already loaded and newrelic doesn't get initialized properly.

I think this makes Lib bit difficult to use.

Thanks

**Comment by patrickhousley** [comment] 2024-02-16 18:45
> my new relic config needs to be fetched first and then initialized

Observation libraries make an assumption that it gets loaded as soon as possible on the page. In the event that it isn't, there is an increased likelihood of missing data. However, the agent should still function properly.

> DOM is already loaded and newrelic doesn't get initialized properly.

Can you elaborate on how newrelic is not initialized properly? Are you getting an error or something?

> I think this makes Lib bit difficult to use.

We want to make the package easier to use. Can you provide some specific feedback on how you would like to see the package or agent changed to make it work better for your needs?

**Comment by master96** [comment] 2024-02-16 19:08
Surely,

I like the lib approach better than script approach.

So as soon as app loads I have snippet like

This is my main.tsx in react app.

fetch('config.json').then((res) => {
const env= await res.json();

const options = env.newrelicConfig;
const newrelicClient = new BrowserAgent(options)
}
).finally(()=>
ReactDOM.createRoot(document.getElementById("root")).render(<App/>))


This does initialize newrelicClient but it doesn't have any API methods
like noticeError. It looks like it's not properly initialized somehow.

Earlier when it was working I didn't have config in my backend so I used to
do something like



const options = hardcoded config;
const newrelicClient = new BrowserAgent(options)

 ReactDOM.createRoot(document.getElementById("root")).render(<App/>)

This works but I am guessing as fetch is async DOM gets loaded and newrelic
doesn't work properly.

**Comment by patrickhousley** [comment] 2024-02-16 19:12
I am sorry @master96 but when you say the agent doesn't work, I really need concrete errors or messages that show what about the agent is not working. Or maybe provide a site where I can look and steps to reproduce. The only thing provided to prove the APIs are not present is a screen shot of the agent being console logged. Like I indicated above, you did not traverse the inheritance tree to find the functions. What happens when you try to call one of the API methods?

**Comment by master96** [comment] 2024-02-16 19:24
Hello Patrick,

Apologies I am writing email from my phone.

So I have console logged browserAgent object in screenshot. If you see type
definition of browserAgent there is no key as API inside it. So when I try
to access that I am getting typescript error.

If you want to reproduce can you try to react app with vite with above
snippet.
Try keeping config.json inside public directory.

Should be easy to reproduce. I don't have broken version deployed to any
link. Can spin up something once I have access to my laptop.

Thanks

**Comment by patrickhousley** [comment] 2024-02-16 19:31
@master96 We do not have the `api` object typed on purpose. You should use `agent.noticeError` and not `agent.api.noticeError`. The `api` object is not part of our public documented API.

**Comment by master96** [comment] 2024-02-16 19:35
Thanks for getting back to me Patrick.

That's what I thought, but If you see OP I don't have noticeError when I
logged object that's the problem. Can you try steps I sent or I can send
code sandbox. Unfortunately I had to fix it so don't have broken version on
link.

Thanks

**Comment by patrickhousley** [comment] 2024-02-16 20:24
@master96 Are you getting an error when you call `newrelicWebClient?.noticeError(e,{some_key:'value'})`?

**Comment by master96** [comment] 2024-02-16 20:30
Hey,

Yes as you can see in screenshot noticeError doesn't exist on
newrelicWebClient
I also tried to use global newrelic from chrome console to test it global
newrelic is able to send errors but I don't receive anything on console.

**Comment by patrickhousley** [comment] 2024-02-16 20:46
@master96 Did you look at the screenshot I posted? I am sorry but we seem to be going in circles. Please try calling the method and provide an actual error the agent is producing.

**Comment by patrickhousley** [comment] 2024-02-22 13:29
@master96 Are you still having issues with the API methods?

**Comment by patrickhousley** [comment] 2024-02-26 17:58
Closing this issue since there has not been any engagement in 4 days.

**Closed by patrickhousley** 2024-02-26 17:58 UTC
Labels: bug
