### ISSUE TITLE
Lighthouse reports duplicate modules

### ISSUE THREAD

**Issue by siuvdlec** [newrelic/newrelic-browser-agent#345] opened 2022-12-15 09:57 UTC
When we run the lighthouse test sometimes this opportunity reported

## Description

![image](https://user-images.githubusercontent.com/3308486/207379591-b1eeff85-6e9d-4bb2-a598-78ee098ccc5e.png)

## Steps to Reproduce

In order to include the agent we follow these instructions https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data  

## Additional context

We use: PRO + SPA

**Comment by patrickhousley** [comment] 2023-02-03 15:06
Hi @siuvdlec and thanks for reporting this issue. We implemented lazy chunk loading for portions of the agent to reduce the initial size of the JS that must be injected into each HTML page. These additional lazy chunks do have a small amount of code overlap by design so that each one can load independently. This is also only occasionally reported most likely because the agent waits for the page load event before it attempts to load these additional lazy chunks.

Please let me know if this resolves your concern and I can close the issue. Thanks.

**Comment by patrickhousley** [comment] 2023-02-23 12:44
Closing due to lack of response.

**Closed by patrickhousley** 2023-02-23 12:44 UTC
Labels: bug, needs-triage
