### ISSUE TITLE
Error: Uncaught ReferenceError: __webpack_require__ is not defined at

### ISSUE THREAD

**Issue by itayeylath** [newrelic/newrelic-browser-agent#902] opened 2024-02-28 10:34 UTC
y OS is Linux-mint and I have a React typescript app. working with yarn (not npm) and docker containers for APISIX and front-end. Also, I have Webpack but without out Webpack configuration file.

I researched solutions on the web and did not find something that worked for me. I also restarted the computer, removed and restarted for docker, and removed and cloned the repository again.

Can you give me solutions with instructions and examples of what to do? :)

After executing 'yarn dev', the server is up, and I get the localhost port. when I open the localhost URL on Chrom the UI is white, and I do not see the app.

In the console getting the error ''Uncaught ReferenceError: webpack_require is not defined at u/newrelic"

**Comment by itayeylath** [comment] 2024-02-28 10:37
> https://new-relic.atlassian.net/browse/NR-233660

I do not have access to Jira on new-relic.atlassian.net.

**Comment by itayeylath** [comment] 2024-02-28 13:14
I fixed it by changing it from-
 "@newrelic/browser-agent": "^1.240.0"
to-
 "@newrelic/browser-agent": "1.240.0"

without the ^

**Comment by patrickhousley** [comment] 2024-02-28 15:44
Hi @itayeylath and thanks for reaching out. I am not sure what issue you are trying to report other than you are getting a webpack error. We use webpack to build our CDN distributions but not the NPM package distribution. Sorry, we would need a reproduction of your use-case to be able to further assist. Regarding your previous message with your fix, I would not recommend that since you will be stuck on an older version of the agent.

**Comment by itayeylath** [comment] 2024-02-28 15:50
Thanks for replaying!
I agree with you. Right now the @newrelic/browser-agent version at the package.json is '1.240.0'. The highest version that works for me and does not come up with a bug is '1.246.1' (at this moment the highest version for the package is '1.252.0').

**Comment by patrickhousley** [comment] 2024-02-28 15:57
How are you importing the browser agent within your code?

**Comment by patrickhousley** [comment] 2024-02-29 17:36
@itayeylath I took a look at our imports for files that rely on webpack globals and did find that we have an issue. I opened https://github.com/newrelic/newrelic-browser-agent/pull/905 to address the problem and I think that will fix the error you are seeing. Thanks again for raising this issue.

**Comment by itayeylath** [comment] 2024-03-03 06:45
I hope it will!


I fixed it by changing it from-
"@newrelic/browser-agent": "^1.240.0"
to-
"@newrelic/browser-agent": "1.240.0"

without the ^

**Comment by patrickhousley** [comment] 2024-03-05 18:09
@itayeylath Version 1.252.1 of the agent has been released with the fix. Could you please verify it works in your use-case? Thanks in advance.

**Comment by itayeylath** [comment] 2024-03-06 07:21
Hey @patrickhousley, appreciate it!
I check it and unfortunately, it is still not working- ''Uncaught ReferenceError: webpack_require is not defined at u/newrelic"

**Comment by patrickhousley** [comment] 2024-03-06 13:43
@itayeylath Can you provide a reproduction of the issue?

**Closed** 2024-03-25 16:07 UTC
Labels: bug
