### ISSUE TITLE
Pro+SPA version 1225 Angular error: Uncaught SyntaxError: Unexpected token ','

### ISSUE THREAD

**Issue by YingcaiSystem1** [newrelic/newrelic-browser-agent#425] opened 2023-02-28 01:22 UTC
Using Pro+SPA, try to upgrade from version 1212 to version 1225 for an Angular project. The App will throw an error:
`Uncaught SyntaxError: Unexpected token ','`

And in the chrome inspector -> network page. Filter the network traffic by the keyword "nr" won't find any. This means there is no monitor traffic(in the old 1212, there was traffic).

I use the inline javascript copied from the New Relic application setting page.

## Description

Issues are mentioned above. 

## Steps to Reproduce

Copied the script, and put it in the index.html's header section. 

## Expected Behavior

No New Relic traffic, throws error
`Uncaught SyntaxError: Unexpected token ','`

## Relevant Logs / Console output

![Capture](https://user-images.githubusercontent.com/104864235/221727922-287bb886-b83c-4944-999b-4c0c38f29b16.PNG)

## Your Environment

Angular 14.3.0
Chrome: 110.0.5481.177
Windows 10

## Additional context

N/A

**Comment by patrickhousley** [comment] 2023-02-28 12:34
@YingcaiSystem1 how are you including the agent? Did you copy and paste the agent snippet from the NR1 UI into your index.html file? If so, can you verify you copied and pasted the entire snippet? Does the snippet only get cutoff during the angular build?

**Comment by YingcaiSystem1** [comment] 2023-02-28 16:08
Hi @patrickhousley here are the steps:

1. Copy the code from URL `https://one.newrelic.com/nr1-core/browser-application-settings/home/<MY ID>?duration=<DURATION TIME>&state=<STATE NUMBER>`
2. The Pro+SPA is selected.
3. Use the right-side copy button to copy all the scripts. (confirmed that the script in my app is the same as the one in new relic)
4. Past in the `index.html` in the header section.
5. Run `ng build`, go to the ./dest folder and open the `index.html` file. The snippet got cut off.

**Comment by patrickhousley** [comment] 2023-02-28 17:10
Per https://github.com/angular/angular-cli/issues/24794 this issue is related to a dependency of the Angular CLI and is fixed in version 15. @YingcaiSystem1 is upgrading the Angular CLI something that you could do for your project?

**Comment by YingcaiSystem1** [comment] 2023-02-28 17:12
@patrickhousley Thanks, that's an option. But I need to discuss it with my team member.

**Comment by patrickhousley** [comment] 2023-02-28 17:12
Thanks @YingcaiSystem1 I am also looking into other options on my end.

**Comment by patrickhousley** [comment] 2023-02-28 17:25
Verified this issue is present back to Angular CLI version 12. I didn't check further due to changes in the Angular CLI project. I also verified this issue is affecting our agent version 1226 and later.

**Comment by patrickhousley** [comment] 2023-02-28 18:38
The root cause of this issue can be traced back to https://github.com/inikulin/parse5/issues/292 and appears to be related to the character length of our initial loader code.

**Closed** 2023-03-06 21:12 UTC
Labels: bug, needs-triage
